### ISSUE TITLE
[Request] Proper changelog for the different versions.

### ISSUE THREAD

**Issue by Splike** [tfedor/Enhanced_Steam#20]
Please :)

**Comment by tfedor** [comment]
You mean new versions or...? So far there's bee only one released on Firefox

**Comment by Splike** [comment]
What I imagined was a proper changelog for the versions found here: https://github.com/tfedor/Enhanced_Steam/releases

If these versions contain extension changes for multiple browsers, the changelog could have [FireFox] and [Chrome] tags.

**Comment by tfedor** [comment]
I see

**Comment by Splike** [comment]
The original creator of ES did it quite well: https://github.com/jshackles/Enhanced_Steam/releases
(Although I don't know why his latest update isn't listed)

**Comment by tfedor** [comment]
https://github.com/tfedor/Enhanced_Steam/releases

**Comment by Splike** [comment]
Thank you! I'll immediately add the releases page to my RSS feed, so I can easily follow the development.
