### ISSUE TITLE
"Default homepage tab" setting gets ignored, always shows "New and Trending"

### ISSUE THREAD

**Issue by snakecase** [tfedor/Enhanced_Steam#51]
Chrome latest, additionally tested with no other extensions enabled in Incognito mode.

**Comment by tfedor** [comment]
Can't replicate (at least at my current version), just to be sure - did you allow the extension in incognito mode?

**Comment by snakecase** [comment]
Yes, sure. Only AS allowed in Incognito (I use Incognito in this case just for testing purposes, the problem occurs in default mode as well).

**Comment by KarlCastle** [comment]
There are 7 options for homepage_tab_selection, only `"remember"` works.

`es_allreleases` and `es_popular` don't seem to be added to the front page at the moment?

The other four, "Popular New Releases", "Top Sellers", "Upcoming", "Specials" don't seem to do anything.

PR created.

**Comment by snakecase** [comment]
> don't seem to be added to the front page at the moment?

Yes, exactly. I thought at first that Steam removed them recently but turns out it was ES's feature all the time.

Also "Remember Previous" just started working for me. Yesterday it wasn't and I checked it several times.

Thank you for your efforts.

**Comment by snakecase** [comment]
Occurs again while logged in. Works normaly after clearing cookies or in Incognito mode but reappears as soon as I log in.

**Comment by MxtOUT** [comment]
That may be because the highlighting on the front page fails currently (fixed by #343 and will be in the next version) and thus the following functions fail, but I'll have to verify once I get homd

**Comment by MxtOUT** [comment]
Yes, that's caused by the failed highlighting
