### ISSUE TITLE
SteamID is undefined

### ISSUE THREAD

**Issue by MilkGames** [tfedor/Enhanced_Steam#65]
As the title says, going to a profile it seems like the steamid is undefined. This breaks SteamRep links but also the copy perma profile tool. 
![image](https://user-images.githubusercontent.com/10010026/52884584-a96a7280-316e-11e9-826f-40401014cebd.png)

**Comment by MilkGames** [comment]
This is only caused when the user isn't logged in.

**Comment by tfedor** [comment]
Should be fixed in v0.9.3

**Comment by MilkGames** [comment]
Fixed!
