### ISSUE TITLE
Does not work running Firefox 56.0.2

### ISSUE THREAD

**Issue by Killogy** [tfedor/Enhanced_Steam#7]
Addon is enable, but there is no any feature enabled on Steam, as if it were disabled, also, do not saves any setting and I can´t browser to other addon menus like PRICE - COMMUNITY - NEWS - ABOUT - CREDITS

**Comment by grahamperrin** [comment]
Cross reference [New Enhanced Steam extension : waterfox](https://www.reddit.com/r/waterfox/comments/amenyw/new_enhanced_steam_extension/)

([Waterfox](https://waterfoxproject.org/) 56.0 was based on Firefox 56.0.2.)

**Comment by RathaWynter** [comment]
Can confirm non-working / inaccessible options pages with FF 55.0.3 as well.

**Comment by Killogy** [comment]
Thank you for fixing this problem, latest addon update is working now. Only some features are not working, I already informed about it here https://github.com/tfedor/Enhanced_Steam/issues/26
